CREATE TABLE PERSON
(
  PId INT NOT NULL,
  PName VARCHAR(20) NOT NULL,
  PRIMARY KEY (PId)
);

CREATE TABLE MODEL
(
  MCC INT NOT NULL,
  MVIN VARCHAR(30) NOT NULL,
  MFuel VARCHAR(1) NOT NULL,
  MEngine VARCHAR(20) NOT NULL,
  MHP INT NOT NULL,
  MWeight INT NOT NULL,
  PRIMARY KEY (MVIN)
);

CREATE TABLE OBD_PARAMETER
(
  OBDHexCode INT NOT NULL,
  OBDLabel VARCHAR(20) NOT NULL,
  PRIMARY KEY (OBDHexCode)
);

CREATE TABLE VEHICLE
(
  VVIN VARCHAR(30) NOT NULL,
  MVIN VARCHAR(30) NOT NULL,
  PRIMARY KEY (VVIN),
  FOREIGN KEY (MVIN) REFERENCES MODEL(MVIN)
);

CREATE TABLE TRACK
(
  TId INT NOT NULL,
  TGPS INT NOT NULL,
  TInitDate DATE NOT NULL,
  TInitHour TIME NOT NULL,
  TInitPos GEOMETRY(POINT),
  TDistance INT NOT NULL,
  TArea INT NOT NULL,
  TPolyLin GEOMETRY(LINESTRING),
  PId INT NOT NULL,
  VVIN VARCHAR(30) NOT NULL,
  PRIMARY KEY (TId),
  FOREIGN KEY (PId) REFERENCES PERSON(PId),
  FOREIGN KEY (VVIN) REFERENCES VEHICLE(VVIN)
);

CREATE TABLE Drives
(
  PId INT NOT NULL,
  VVIN VARCHAR(30) NOT NULL,
  PRIMARY KEY (PId, VVIN),
  FOREIGN KEY (PId) REFERENCES PERSON(PId),
  FOREIGN KEY (VVIN) REFERENCES VEHICLE(VVIN)
);

CREATE TABLE SAMPLE
(
  SName VARCHAR(20) NOT NULL,
  STs BIGINT NOT NULL,
  SFloatValue FLOAT NOT NULL,
  SIntValue INT NOT NULL,
  OBDHexCode INT NOT NULL,
  TId INT NOT NULL,
  PRIMARY KEY (STs, OBDHexCode),
  FOREIGN KEY (OBDHexCode) REFERENCES OBD_PARAMETER(OBDHexCode),
  FOREIGN KEY (TId) REFERENCES TRACK(TId),
  UNIQUE (SName)
);